---
name: Test-Command
version: 0.02
author:
  - 'Daniel B. Boorstein <danboo@cpan.org>'
abstract: Test routines for external commands
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Simple: 0.62
provides:
  Test::Command:
    file: lib/Test/Command.pm
    version: 0.02
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
